### ISSUE TITLE
Mean of 100 not showing up

### ISSUE THREAD

**Issue by dsoegijono** [timhabermaas/cubemania#10]
<img width="203" alt="screen shot 2017-11-09 at 16 22 08" src="https://user-images.githubusercontent.com/867840/32589744-666617da-c56a-11e7-9fde-bd5cbc168f1d.png">

It was working for a while, but at some point I refreshed the page and it's gone, and it hasn't come back since.

Also, any chance for an "average of 100"?

**Comment by dsoegijono** [comment]
Closing this. I think it's because I have a DNF within the 100 😶 

(but average of 100 would still be great)

**Comment by timhabermaas** [comment]
Ah yes, a DNF kills every mean. I think I used mean of 100 instead of average of 100 because that was common in the community a while ago (e.g. Prisma Puzzle Timer used it). I'll probably change it to average of 100.
