### ISSUE TITLE
"Longtime" chart dates are flipped (?)

### ISSUE THREAD

**Issue by dsoegijono** [timhabermaas/cubemania#9]
<img width="500" alt="screen shot 2017-11-08 at 11 14 48" src="https://user-images.githubusercontent.com/867840/32524938-392ae330-c476-11e7-98ab-4bbcd225a29c.png">

I think the "to" and "from" dates are flipped.

**Comment by timhabermaas** [comment]
Thanks for reporting! I fixed it: c7457d3576f2f7dae3cbbb6f2cd12d46f0da2796

Not sure how no one (including me) noticed this before. This bug must have been in existence for several years. 🙈

**Comment by dsoegijono** [comment]
👍 thanks for the quick fix! I guess people don't really care since the chart itself is correct 🙂
